site_name: 散修讀經典
site_url: https://edtao168.github.io/jingdian/

theme:
  name: material
  language: zh-Hant
  palette:
    primary: indigo
  features:
    #- navigation.tabs
    - navigation.indexes
    - navigation.sections
    - navigation.top

plugins:
  - search
  - awesome-pages
